### ISSUE TITLE
How can I NER tag already tokenized text?

### ISSUE THREAD

**Issue by Coffeexiudou** [Lynten/stanford-corenlp#13]
Or load my  own custom dictionary

**Comment by Lynten** [comment]
The user dictionary problem, please refer to [the CoreNLP issue](https://github.com/stanfordnlp/CoreNLP/issues/317). 

Here is an example for Chinese language: 
You can add your dictionary path to the line in the `StanfordCoreNLP-chinese.properties` file, which is compressed in the `stanford-chinese-corenlp-2017-06-09-models.jar` file.
```
segment.serDictionary = edu/stanford/nlp/models/segmenter/chinese/dict-chris6.ser.gz,user_dict.txt
```
However, "the words in the dictionary are just features. Strong features, to be sure, but it can't deterministically split on dictionary words."
