### ISSUE TITLE
running slow!

### ISSUE THREAD

**Issue by yzho0907** [Lynten/stanford-corenlp#24]
any idea why it runs quite slow and how to solve it??

**Comment by Lynten** [comment]
Please refer to #6. Let me know if you still have problems.

**Comment by yzho0907** [comment]
can i ask u is it one of the reason is that running corenlp in this way requires Internet connection? and i am now using nltk to load stanford models first, then process corenlp functions, it runs much more faster (some of the functions just cost within 1s)!

**Comment by Lynten** [comment]
No, it does not require internet connection. It does cost time to start the Java server. When it is done, it processes faster. Please take a look at the example code in #6.

**Comment by The-Gupta** [comment]
@yzho0907 Could you add references to how you're using NLTK to load Stanford models first, then process CoreNLP functions to runs much faster? Also, could you provide codes?

**Comment by yzho0907** [comment]
@The-Gupta here just an example:
import os
from nltk.parse import stanford
os.environ['STANFORD_PARSER'] = 'yourpath/Downloads/stanford-parser-full-2018-02-27/stanford-parser.jar'
os.environ['STANFORD_MODELS'] = 'yourpath/stanford-parser-full-2018-02-27/stanford-parser-3.9.1-models.jar'
cn_parser = stanford.StanfordParser(model_path="yourpath/chinesePCFG.ser.gz")
