### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by mjrinker** [Lynten/stanford-corenlp#25]
I'm getting a file not found error as shown below:

`Traceback (most recent call last):
File "D:/Users/[user]/Documents/NLP/arabic_tagger/build_model.py", line 6, in <module>
    nlp = StanfordCoreNLP(corenlp_path, lang='ar', memory='4g')`
`File "C:\Users\[user]\AppData\Roaming\Python\Python36\site-packages\stanfordcorenlp\corenlp.py", line 46, in __init__`
`if not subprocess.call(['java', '-version'], stdout=subprocess.PIPE, stderr=subprocess.STDOUT) == 0:`
`File "C:\Users\[user]\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 267, in call`
`    with Popen(*popenargs, **kwargs) as p:`
`File "C:\Users\[user]\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 709, in __init__`
`    restore_signals, start_new_session)`
`File "C:\Users\[user]\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 997, in _execute_child`
`    startupinfo)`
`FileNotFoundError: [WinError 2] The system cannot find the file specified`

I have used this wrapper before and am using it in the same way as always:

`corenlp_path = 'D:/Users/[user]/Desktop/StanfordCoreNLP/Full_CoreNLP_3.8.0'`
`nlp = StanfordCoreNLP(corenlp_path, lang='ar', memory='4g')`

Just to be sure, I downloaded version 3.8.0 as well as the Arabic models and made sure they are in the path specified. I'm wondering if the FileNotFoundError is not referring to the CoreNLP path but something else... subprocess.py is in the correct directory. So yeah... not sure what's wrong/what to do.

Thanks!

**Comment by mjrinker** [comment]
I posted this and realized that I don't have Java installed. I'll install and then check back here.

**Comment by mjrinker** [comment]
Yeah, that was it. I also had to add Java to the path. Haha I feel dumb for posting this and then solving it a second later. But hopefully it helps someone in the future!

**Comment by 99sun99** [comment]
Thanks! it really helps!

**Comment by sahityasridhar08** [comment]
How do you add Java to the path ?

**Comment by mjrinker** [comment]
@sahityasridhar08 
Add Java to path:
https://www.baeldung.com/java-home-on-windows-7-8-10-mac-os-x-linux

If that link doesn't work for you, search Google for "Add Java to path" and make sure to choose a guide that includes steps specific to your OS (Windows, macOS, Linux, etc.)
