### ISSUE TITLE
 INFO:root:Waiting until the server is available.

### ISSUE THREAD

**Issue by antoineChammas** [Lynten/stanford-corenlp#27]
Hi, I'm trying to use this library for a project where I would need corefence resolution. I was testing out the test.py file and this kept on showing indefinitely, how do I fix this?

Thanks in advance.

**Comment by xiedaxia1hao** [comment]
Hi, have you figured it out? I have also meet this issue.

**Comment by antoineChammas** [comment]
Hi, no, I just started using something else for coreference resolution.

**Comment by matanrak** [comment]
I had the same issue, try this stripped down version of corenlp.py I made, it also fixed the issues I had for mac (python didn't have the permission to view the current connections so it couldn't verify which ports were being used so instead I used one port and run corenlp through a with: to make it it is closed properly).
This version is a little bit of a botch, but hey, it works. 
https://github.com/matanrak/NaturalIntelligenceExercise/blob/master/corenlp.py

**Comment by matanrak** [comment]
The solution for me was to add '--add-modules java.se.ee' after the 'java' when opening the server, this fixes compatibility errors with java 9.

Also you might want to take a look at a stripped down version of corenlp.py I made:
https://github.com/matanrak/NaturalIntelligenceExercise/blob/master/corenlp.py

**Comment by antoineChammas** [comment]
Okay, thanks!

**Comment by dzzyt** [comment]
my issue was with 32b java installed, try 'java -d64' in cmd and see if it's working! if it isn't just install it and run it again.

**Comment by kevinmraz** [comment]
Hi! antoine,have you solved this problem? @antoineChammas

**Comment by kevinmraz** [comment]
兄弟这个问题解决了吗？：） @xiedaxia1hao

**Comment by xiedaxia1hao** [comment]
@kevinmraz Not yet.. I just used the other package..

**Comment by kevinmraz** [comment]
fine,thx! btw, could u please tell me what another package u used?

**Comment by xiedaxia1hao** [comment]
@kevinmrazh Hi! If you are doing Chinese NLP, you can use jieba

**Comment by kevinmraz** [comment]
Of course I have already used it. But to b honest, it did not work very well~~

**Comment by stuhci** [comment]
I have the same issue. I try to increase the sleeping time under CoreNLP.py line 114 and it works.

**Comment by jorgeqscholz** [comment]
> I have the same issue. I try to increase the sleeping time under CoreNLP.py line 114 and it works.

Thanks. I had the same issue and increasing it to 10 made it work.
