### ISSUE TITLE
TypeError: can't pickle _thread.lock objects When trying to pickle.dump model

### ISSUE THREAD

**Issue by oren1k** [Lynten/stanford-corenlp#28]
I'm trying to save the model to use it without having to download and read the data itself every time but I get an error:
```

from stanfordcorenlp import StanfordCoreNLP
nlp = StanfordCoreNLP("/NLP_models/stanford-corenlp-full-2018-01-31")
pickle.dump(nlp, open("/NLP_models/pickled_wrapped_nlp", "w"))
```

And the error:
```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't pickle _thread.lock objects
```

What can I do?
Thanks

**Comment by Lynten** [comment]
We can't pickle the StanfordCoreNLP object. [Use an Existing Server](https://github.com/Lynten/stanford-corenlp#use-an-existing-server) may help you.
