### ISSUE TITLE
JSONDecoderError: Expecting Value line 1 column 1

### ISSUE THREAD

**Issue by yceny** [Lynten/stanford-corenlp#32]
I was trying to do NER with my text

from stanfordcorenlp import StanfordCoreNLP

documents = pd.read_csv('some csv file')['documents'].values.tolist()
text = documents[0] ## test is a string

nlp = StanfordCoreNLP('my_path\stanford-corenlp-full-2018-02-27') ## latest version
print(nlp.ner(text))

But I keep getting this error

raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by hexingren** [comment]
The same issue happened to the example code. Did anyone solve it?

**Comment by Lynten** [comment]
Check the comment of #16.

**Comment by hexingren** [comment]
Hello Lynten,

After setting the debug mode, I found the following message.

"""
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:9001 "POST /?properties=%7B%27annotators%27%3A+%27ner%27%2C+%27outputFormat%27%3A+%27json%27%7D&pipelineLanguage=en HTTP/1.1" 500 132
"""

I tried several Python wrappers with the newest version of CoreNLP (V3.9.1) and they all threw out "HTTPError: 500 Server Error" when it came to NER. However, the POS tagger would work. Does the message above suggest that there's something wrong with the new server? Thanks.

**Comment by zhuzixiao** [comment]
Dear Lynten,

I have found the root cause to this problem and solve it in [this way](https://github.com/Lynten/stanford-corenlp/issues/16#issuecomment-418582137)

Would you please consider about adding those code to your next version of corenlp?

Thank you very much.

**Comment by zhang402115** [comment]
i also came across this problem, especially when the length of text exceeds 2000 lines in python
