### ISSUE TITLE
How to use stanfordcorenlp to replace all pronouns in a sentence with the nouns

### ISSUE THREAD

**Issue by manavpolikara** [Lynten/stanford-corenlp#34]
How can I use standfordcorenlp to replace all pronouns with their nouns in a sentence. For example the sentence is : Fred Rogers lives in a house with pets. It is two stories, and he has a dog, a cat, a rabbit, three goldfish, and a monkey.

This needs to be converted to : Fred Rogers lives in a house with pets. House is two stories, and Fred Rogers has a dog, a cat, a rabbit, three goldfish, and a monkey.

I had used the below code 
nlp = StanfordCoreNLP(r'G:\JavaLibraries\stanford-corenlp-full-2017-06-09', quiet=False)
props = {'annotators': 'coref', 'pipelineLanguage': 'en'}

text = 'Barack Obama was born in Hawaii.  He is the president. Obama was elected in 2008.'
result = json.loads(nlp.annotate(text, properties=props))

mentions = result['corefs'].items()

Although, I cannot understand how to read through mentions and perform what I want to do.

**Comment by Lynten** [comment]
Check the [wiki](https://github.com/Lynten/stanford-corenlp/wiki/Coreference-Resolution) which may help you.

**Comment by manavpolikara** [comment]
Thanks Lynten. I was able to achieve my task. Only question is what does the representative flag mean? 
I assumed that the noun should have the flag as true and the pronouns should have the flag as false. 
Is that correct ?

**Comment by Lynten** [comment]
I'm not familiar with this either. According to [CoreNLP](https://stanfordnlp.github.io/CoreNLP/faq.html#what-is-the-format-of-the-xml-output-for-coref), "each chain is a block describing each of the mentions. One mention will be labeled the representative mention".

**Comment by manavpolikara** [comment]
lol yea, I couldn't find anything else on their website either. I have posted a question on stackoverflow tagging CoreNLP..

Anyways, thank you for your help 😃
