### ISSUE TITLE
Expecting nlp.dcoref  

### ISSUE THREAD

**Issue by pbms** [Lynten/stanford-corenlp#4]
Nice work. Is there a possibility to make nlp.dcoref  in the next release?

**Comment by purvanshi** [comment]
I have made a pull request for the same. You can also check out the code on
[My forked repository](https://github.com/purvanshi/stanford-corenlp)

**Comment by Lynten** [comment]
Sorry for the late reply. Sure it will. I have considered the user-friendly implementation for a long time.

**Comment by euler314** [comment]
This would be extremely useful, and also expected from the interface. I wonder if there are any updates on this?

**Comment by Lynten** [comment]
The new version has added the coref function. Check [wiki](https://github.com/Lynten/stanford-corenlp/wiki/Coreference-Resolution).
