### ISSUE TITLE
中文指代消解没有输出

### ISSUE THREAD

**Issue by chenjiaxiang** [Lynten/stanford-corenlp#41]
我在general api里添加dcoref的时候，没有输出结果
![3](https://user-images.githubusercontent.com/19178992/40269948-bf00585e-5bb7-11e8-90bd-bafe4c3a2859.JPG)
![2](https://user-images.githubusercontent.com/19178992/40269973-12ac6c72-5bb8-11e8-9b7f-dfae8af9050d.JPG)

但是pipeline中去掉dcoref,就会有正确的输出，英文部分并不存在这个问题，我在源码中看到中文和英文的处理代码除了model文件之外几乎没有区别，请问是这个wrapper现在还不支持中文的指代消解吗？

下面的代码是没有问题的测试代码

![1](https://user-images.githubusercontent.com/19178992/40269936-9f96b544-5bb7-11e8-82c9-2cb386d8d07e.jpg)

**Comment by zh215021** [comment]
您好，请问您解决这个问题了么？

**Comment by iamlxb3** [comment]
我直接使用nlp.coref()报错：JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by MingxuanLiu** [comment]
您好，请问您的这个问题解决了吗？

**Comment by chenjiaxiang** [comment]
> 您好，请问您的这个问题解决了吗？

我的这个问题解决了，但是应该是与代码相关的。不知道你代码怎么写的

**Comment by MingxuanLiu** [comment]
> > 您好，请问您的这个问题解决了吗？
> 
> 我的这个问题解决了，但是应该是与代码相关的。不知道你代码怎么写的
from stanfordcorenlp import StanfordCoreNLP
# text = '刘明烜你好，我是赖冠霖。请打开下面这个链接，领取会员奖励。'
text = '刘明烜 你好 ， 我 是 赖冠霖 。 请 打开 下面 这个 链接 ， 领取 会员 奖励 。 '
output = nlp.annotate(text, properties={
  'annotators': 'tokenize,dcoref,relation',
  'outputFormat': 'json'
  })
print(output)

您好，我是这样写的。

**Comment by MingxuanLiu** [comment]
> > 您好，请问您的这个问题解决了吗？
> 
> 我的这个问题解决了，但是应该是与代码相关的。不知道你代码怎么写的
from stanfordcorenlp import StanfordCoreNLP
nlp = StanfordCoreNLP('/data/lmx/corenlp/stanford-corenlp-full-2018-10-05', lang='zh')
sentence = '刘明烜你好，我是赖冠霖。请打开下面这个链接，领取会员奖励。'
output = nlp.annotate(text, properties={
  'annotators': 'tokenize,dcoref,relation',
  'outputFormat': 'json'
  })
print(output)
您好，我是这样写的。

**Comment by MingxuanLiu** [comment]
> > 您好，请问您的这个问题解决了吗？
> 
> 我的这个问题解决了，但是应该是与代码相关的。不知道你代码怎么写的

from stanfordcorenlp import StanfordCoreNLP
nlp = StanfordCoreNLP('/data/lmx/corenlp/stanford-corenlp-full-2018-10-05', lang='zh')
sentence = '孙某你好，我是赖某。请打开下面这个链接，领取会员奖励。'
output = nlp.annotate(text, properties={
'annotators': 'tokenize,dcoref,relation',
'outputFormat': 'json'
})
print(output)
您好，我是这样写的。

**Comment by chenjiaxiang** [comment]
> > > 您好，请问您的这个问题解决了吗？
> > 
> > 
> > 我的这个问题解决了，但是应该是与代码相关的。不知道你代码怎么写的
> 
> from stanfordcorenlp import StanfordCoreNLP
> nlp = StanfordCoreNLP('/data/lmx/corenlp/stanford-corenlp-full-2018-10-05', lang='zh')
> sentence = '孙某你好，我是赖某。请打开下面这个链接，领取会员奖励。'
> output = nlp.annotate(text, properties={
> 'annotators': 'tokenize,dcoref,relation',
> 'outputFormat': 'json'
> })
> print(output)
> 您好，我是这样写的。

处理方式是pieline形式,annotator中应该包含更多的处理方式，具体你可以看下官方文档，其中有讲。

**Comment by MingxuanLiu** [comment]
> > > > 您好，请问您的这个问题解决了吗？
> > > 
> > > 
> > > 我的这个问题解决了，但是应该是与代码相关的。不知道你代码怎么写的
> > 
> > 
> > from stanfordcorenlp import StanfordCoreNLP
> > nlp = StanfordCoreNLP('/data/lmx/corenlp/stanford-corenlp-full-2018-10-05', lang='zh')
> > sentence = '孙某你好，我是赖某。请打开下面这个链接，领取会员奖励。'
> > output = nlp.annotate(text, properties={
> > 'annotators': 'tokenize,dcoref,relation',
> > 'outputFormat': 'json'
> > })
> > print(output)
> > 您好，我是这样写的。
> 
> 处理方式是pieline形式,annotator中应该包含更多的处理方式，具体你可以看下官方文档，其中有讲。

好的！！！感激！！！！！

**Comment by MingxuanLiu** [comment]
> > > > 您好，请问您的这个问题解决了吗？
> > > 
> > > 
> > > 我的这个问题解决了，但是应该是与代码相关的。不知道你代码怎么写的
> > 
> > 
> > from stanfordcorenlp import StanfordCoreNLP
> > nlp = StanfordCoreNLP('/data/lmx/corenlp/stanford-corenlp-full-2018-10-05', lang='zh')
> > sentence = '孙某你好，我是赖某。请打开下面这个链接，领取会员奖励。'
> > output = nlp.annotate(text, properties={
> > 'annotators': 'tokenize,dcoref,relation',
> > 'outputFormat': 'json'
> > })
> > print(output)
> > 您好，我是这样写的。
> 
> 处理方式是pieline形式,annotator中应该包含更多的处理方式，具体你可以看下官方文档，其中有讲。

我按照官方文档把annotator改成了这样'annotators': 'tokenize, ssplit, pos, lemma, ner, parse, coref'，还是不行，可以问下您的代码是怎么写的吗？而且这样写了以后都不进行分词了。

**Comment by chenjiaxiang** [comment]
我改了改工具里的shell脚本，我把我的文件发给你，对应位置的截图和一个输出结果，总共三个文件，你自己看一下吧



1289609489@qq.com
 
发件人： Niki_Liu
发送时间： 2019-11-21 12:26
收件人： Lynten/stanford-corenlp
抄送： chenjiaxiang; Author
主题： Re: [Lynten/stanford-corenlp] 中文指代消解没有输出 (#41)
您好，请问您的这个问题解决了吗？
我的这个问题解决了，但是应该是与代码相关的。不知道你代码怎么写的
from stanfordcorenlp import StanfordCoreNLP
nlp = StanfordCoreNLP('/data/lmx/corenlp/stanford-corenlp-full-2018-10-05', lang='zh')
sentence = '孙某你好，我是赖某。请打开下面这个链接，领取会员奖励。'
output = nlp.annotate(text, properties={
'annotators': 'tokenize,dcoref,relation',
'outputFormat': 'json'
})
print(output)
您好，我是这样写的。
处理方式是pieline形式,annotator中应该包含更多的处理方式，具体你可以看下官方文档，其中有讲。
我按照官方文档把annotator改成了这样'annotators': 'tokenize, ssplit, pos, lemma, ner, parse, coref'，还是不行，可以问下您的代码是怎么写的吗？而且这样写了以后都不进行分词了。

**Comment by xiayulehuan** [comment]
你好可以给我发一份吗？ 我也在做中文指代消解。谢谢

**Comment by xiayulehuan** [comment]
你好，你收到文件了吗，可以给我发一份吗？997028703@qq.com
