### ISSUE TITLE
Connecting to a unavailable server doesn't throw exception

### ISSUE THREAD

**Issue by GanadiniAkshay** [Lynten/stanford-corenlp#45]
When trying to connect to a existing server that is unavailable the code throws no exception and becomes unresponsive while trying to annotate leading to timeout errors.

**Comment by laurentb** [comment]
https://github.com/Lynten/stanford-corenlp/pull/51 should fix it

I've merged it in https://github.com/geneanet/stanford-corenlp among other fixes

**Comment by GanadiniAkshay** [comment]
I already made a pr #46 to fix it...not yet merged though.
We went ahead with our own fork

**Comment by GanadiniAkshay** [comment]
The pr #46 should have fixed this so closing the issue
