### ISSUE TITLE
Socket Connect Hanging

### ISSUE THREAD

**Issue by jryga** [Lynten/stanford-corenlp#7]
On Mac OSX connecting to the socket may cause hanging.  Adding a short delay before the first check fixes it.

**Comment by Lynten** [comment]
Thanks. I will test it later.

**Comment by Tbabm** [comment]
I encountered the same problem on Mac OSX.
Jryga's solution works for me.

**Comment by Lynten** [comment]
@jryga Hi, the new release add your fix, thanks.
