### ISSUE TITLE
why it's can't work  on the  Simple Usage

### ISSUE THREAD

**Issue by hdray123** [Lynten/stanford-corenlp#9]
i just  run the example's Simple Usage  
/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7 /Users/shenglong123/Desktop/bbb/cc.py
[main] INFO CoreNLP - --- StanfordCoreNLPServer#main() called ---
[main] INFO CoreNLP - setting default constituency parser
[main] INFO CoreNLP - warning: cannot find edu/stanford/nlp/models/srparser/englishSR.ser.gz
[main] INFO CoreNLP - using: edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz instead
[main] INFO CoreNLP - to use shift reduce parser download English models jar from:
[main] INFO CoreNLP - http://stanfordnlp.github.io/CoreNLP/download.html
[main] INFO CoreNLP -     Threads: 8
[main] INFO CoreNLP - Starting server...
[main] INFO CoreNLP - StanfordCoreNLPServer listening at /0:0:0:0:0:0:0:0:9000

i wait half of a hour
however it is not print anythings 
i run it in my MACOS and ubuntu  
the stanford-corenlp-full-2017-06-09 I also put on  /Users/shenglong123/desktop/stanford-corenlp-full-2017-06-09 
it contain
CoreNLP-to-HTML.xsl			joda-time-2.9-sources.jar
LIBRARY-LICENSES			joda-time.jar
LICENSE.txt				jollyday-0.4.9-sources.jar
Makefile				jollyday.jar
README.txt				patterns
SemgrexDemo.java			pom.xml
ShiftReduceDemo.java			protobuf.jar
StanfordCoreNlpDemo.java		slf4j-api.jar
StanfordDependenciesManual.pdf		slf4j-simple.jar
build.xml				stanford-corenlp-3.8.0-javadoc.jar
corenlp.sh				stanford-corenlp-3.8.0-models.jar
ejml-0.23-src.zip			stanford-corenlp-3.8.0-sources.jar
ejml-0.23.jar				stanford-corenlp-3.8.0.jar
input.txt				sutime
input.txt.xml				tokensregex
javax.json-api-1.0-sources.jar		xom-1.2.10-src.jar
javax.json.jar				xom.jar

I would appreciate it if you could give me some advice,thanks

**Comment by echan00** [comment]
Did you solve your problem? How long does it take to load?

**Comment by hdray123** [comment]
> Did you solve your problem? How long does it take to load?

sorry  I have forget how did I slove it  ,it's too long for now.

**Comment by echan00** [comment]
Yes I did my Java version wasn't up to date
